### ISSUE TITLE
[BUG] The color of the notification icon is not correct

### ISSUE THREAD

**Issue by hydrielax** [3cn-ecn/nantralPlatform#1077]
# Description

When we have unread notifications, the color of the badge is orange instead of red
<img width="131" alt="image" src="https://github.com/3cn-ecn/nantralPlatform/assets/70099779/85af8214-3823-4296-86f4-28ae825ef114">

## Why is this a bug?

Orange is dedicated to errors in our design system

## How to fix?

Replace the color by the `primary` color in the code

**Comment by prafulnigam** [comment]
No Worries ! Will work over the issue.

**Comment by hydrielax** [comment]
Done with #1169
