### ISSUE TITLE
[BUG] Webmail not available after server reboot

### ISSUE THREAD

**Issue by hydrielax** [3cn-ecn/nantralPlatform#1085]
## Describe the bug

Webmail not available after server reboot.

Steps:
* reboot the server
* up all containers: `dcf up -d`
* the main website works, nginx, is running, but the webmail is not accessible

Hot fix:
* I fix it by restarting the front service: `dcf restart front`

## Expected behavior

We should not have to restart the front service to make mail working after reboot (we often do server reboot for updates, and we can easily forget about emails if we don't check)

## Possible fix

Add a health-check on front service ? (or imap or webmail service)

**Comment by charles-zablit** [comment]
> Add a health-check on front service ?

This seems to be the only way around this.
