### ISSUE TITLE
[TICKET] Bouton "Renvoyer le mail de validation"

### ISSUE THREAD

**Issue by hydrielax** [3cn-ecn/nantralPlatform#1089]
# Description

Certains utilisateurs ne reçoient pas le mail de validation pour créer leur compte. Il nous faudrait une page intermédiaire, ou, s'ils essaient de se connecter avec ces identifiants, que ces identifiants sont reconnus mais que le mail n'est pas validé, on arrive sur une page spéciale expliquant qu'il faut valider le compte avant, avec un bouton pour renvoyer le mail de validation.

# Definition of done

- [ ] En tant qu'utilisateur, je peux demander à renvoyer le mail de validation
- [ ] En tant qu'utilisateur, on me propose aussi de renvoyer le mail si j'essaie de me connecter

# Technical strategy

*Describe in multiple steps how you will implement your ticket. The more precise you are, the easier it will be to develop afterwards.*

- [ ] ...
- [ ] ...

**Comment by rravelli** [comment]
@hydrielax Il y a une petite subtilité dans le ticket. Il n'y a pas de moyen de savoir si un compte est inactif parce qu'il a été désactivé ou parce que son mail n'a pas été validé. C'est vrai uniquement pour les comptes créé à partir du mail de centrale parce qu'ils ne génèrent pas un objet **Temporary access requests**.  
Solution temporaire : considérer qu'un compte inactif est un compte dont le mail n'est pas validé.

**Comment by hydrielax** [comment]
Je te laisse carte blanche, j'avoue ne pas tout comprendre 😅 Ce que je peux te dire par contre c'est que pour les mails temporaires on a aussi un champ is_actif dans TemporaryRequest donc ça peut compliquer un peu la donne.

**Comment by rravelli** [comment]
C'est un peu le bordel oui. Heureusement que ça va être refait prochainement 👀
