### ISSUE TITLE
[BUG] Le filtre shotgun sur la page d'event ne fonctionne pas

### ISSUE THREAD

**Issue by rravelli** [3cn-ecn/nantralPlatform#1104]
Le filtre shotgun de la page d'event ne fait pas apparaitre les événements de type shotgun

## To Reproduce
1. Aller sur la page d'event
2. Cliquer sur plus de filtre
3. Sélectionner la case shotgun
4. Aucun événement apparait

## Expected behavior
Les événement de type shotgun devrait apparaitre

**Comment by hydrielax** [comment]
# Investigation

La définition d'un shotgun dans le backend et le frontend est différente.

Dans le backend : 
* un event est un shotgun si le nombre max de participant est non-null

Dans le frontend : 
* un event est un shotgun si le nombre max de participants est non-null OU la date de début ou de fin des inscriptions est non-nulle

Le bouton "Shotgun !" utilise la définition du frontend
Le filtre "Shotgun" utilise la définition du backend

# Solution

* Modifier la définition du shotgun dans le viewset backend. Attention vu qu'on utilise des booleans pour les query params le backend doit aussi support `is_shotgun=false` (i.e. on exclut tous les shotguns) même si cette feature n'est pas utilisée dans le front (quand la case est décochée on met `is_shotgun=undefined` pour avoir tous les events). Ça permet d'avoir une cohérence sur tous les champs boolean de l'api

**Comment by Archit-Kohli** [comment]
Je peux faire ça, s'il vous plaît donnez moi cette issue
