### ISSUE TITLE
[TICKET] Meilleurs comptes temporaires et vérification des mails

### ISSUE THREAD

**Issue by rravelli** [3cn-ecn/nantralPlatform#1112]
# Description

Amélioration du fonctionnement de la vérification par mail et comptes temporaires.
Tous les emails (de centrale nantes ou non) sont désormais stockés dans le champ `email` de `User`.
Le champ `is_email_valid`, `False` par défaut, permet de détecter qu'un utilisateur n'a pas validé son adresse email.
Lorsque l'email est vérifié il est mis à `True` est n'est plus jamais modifié.
Concernant les comptes temporaires, le champ `invitation` de `User` permet d'enregister la clé d'invitation utilisée. Le modèle Id registrations contient un champ `expires_at` qui donne la date d'expiration de l'invitation. Lorsque le compte devient permanent, le champ `invitation` passe à `null`.

Pour le changement de l'adresse email existante un champ `email_next`  permet de stocker la nouvelle adresse tant que l'email n'est pas validée. Une fois l'email validée le champ `email` est remplacé par `email_next`

# Definition of done

*The ticket can be considered as done if all theses criteria are completed:*
- [ ] La vérification que l'email est valide se fait via un champ `is_email_valid` (et non plus `is_active`)
- [ ] Les comptes temporaires sont détectés via un nouveau champ `invitation`
- [ ] Ajouter la documentation sur l'authentification

# Technical strategy

- [ ] Ajout des champs `is_email_valid`, `invitation` et `email_next` au model User
- [ ] Ajout du champ `expires_at` sur le modèle IDRegistration
- [ ] Suppression du modèle `TemporaryAccount` avec les migrations nécessaires
- [ ] Changement du backend d'authentification (suppression de EmailBackend)

![375764653_983143659523866_7992225048537432880_n](https://github.com/3cn-ecn/nantralPlatform/assets/112650656/0590bb75-17f9-40b1-a2d9-bf85a40f8292)

**Comment by hydrielax** [comment]
@rravelli Ce ticket est done du coup ?

**Comment by rravelli** [comment]
> @rravelli Ce ticket est done du coup ?

Yep
