### ISSUE TITLE
Amélioration des groupes : recherche, filtrage et statuts pour les membres

### ISSUE THREAD

**Issue by unitrium** [3cn-ecn/nantralPlatform#184]
- [x] Réaliser un bon affichage des membres
- [ ] Distinguer le président (cf #674)
- [x] Peut-être essayer d'uniformiser les champs du poste ?

**Comment by hydrielax** [comment]
Reste à faire :

- [ ] Refaire l'affichage des membres en bulles (comme la liste des clubs, prends moins de place)
- [ ] Masquer dans une sous page les anciens membres
- [ ] Pour l'édition des membres, définir l'ordre avec un cliquer-glisser
- [ ] Ajouter un champ "adresse mail de contact" et un champ lieu et heure de réunion hebdomadaire/mensuelle/etc

**Comment by hydrielax** [comment]
Moved to #1066
