### ISSUE TITLE
Ajout d'un mode sombre

### ISSUE THREAD

**Issue by unitrium** [3cn-ecn/nantralPlatform#426]
Parce que pourquoi pas ? C'est la mode <br/> Proposé parCEM

**Comment by hydrielax** [comment]
J'y ai pensé aussi mais c'est LONG à faire ...

**Comment by unitrium** [comment]
Oui y a une raison pour laquelle github a mis des années avant de sortir son mode sombre

**Comment by hydrielax** [comment]
En pratique pour la gestion des cookies et tout je pourrais reprendre le code js que j'avais fait pour le site cerf'lock, le plus long ce sera surtout de recompiler bootstrap avec des couleurs sombres...

**Comment by hydrielax** [comment]
Pour le frontend react, on pourra facilement ajouter un mode sombre en utilisant les thèmes de mui

**Comment by hydrielax** [comment]
Ajouté dans la v2 en react
