### ISSUE TITLE
Support des shotguns

### ISSUE THREAD

**Issue by charles-zablit** [3cn-ecn/nantralPlatform#531]
On pourrait faire quelque chose de plus propre que le Google Sheet que la pluspart des assos utilisent.

**Comment by unitrium** [comment]
Yep j'y avais pensé ce serait génial, il faudra juste bien s'assurer qu'on tient la charge quand 200-300 personnes veulent obtenir leur place de tonus (ça arrive jamais rip les fox et leur tonus annulé) mais un shotgun qui rate parce que l'infrastructure marche pas (onboard je te regarde), il y a pas pire.

**Comment by hydrielax** [comment]
Un système de shotgun à été implémenté dans la v2 en react, à tester jusqu'à combien de personnes simultanées notre serveur peut encaisser. Si besoin il faudra peut-être passer par des fonctions serverless (type AWS)

**Comment by hydrielax** [comment]
Done in #1016
