### ISSUE TITLE
[TICKET] Migrer le générateur de signature vers React

### ISSUE THREAD

**Issue by charles-zablit** [3cn-ecn/nantralPlatform#626]
Le generateur de signature utilise actuellement un script basé sur jQuery.

Le passer en React nous permettrai de le mettre au goût du jour de notre codebase.

**Comment by hydrielax** [comment]
Les différentes idées à ajouter pour le générateur de signature :
* passer le code en react
* générer toute la signature automatiquement en fonction du compte de l'utilisateur (nom, année, option, mail, ...)
* ajouter une liste déroulante avec des modèles de signatures, au choix :
    * une signature "simple" : année et option (si dispo) seulement
    * une signature "complète" : la même mais avec la liste de tous les rôles dans les clubs et assos
    * une signature pour chaque club/asso où l'utilisateur est membre, où le logo de centrale est remplacé par le logo du club (si disponible)
* conserver la possibilité de modifier la signature mais avec une seule case formulaire, où les barres jaunes sont représentées par des "---" pour pouvoir entièrement personnaliser la signature et modifier l'emplacement et le nombre des barres jaunes

**Comment by hydrielax** [comment]
Done with https://github.com/3cn-ecn/nantralPlatform/pull/1146
