### ISSUE TITLE
Architecture du backend

### ISSUE THREAD

**Issue by hydrielax** [3cn-ecn/nantralPlatform#634]
Quelques réflexions pour améliorer la structure du site :

- [ ] Grouper toutes les apps de type "group" dans un même dossier `apps > groups`.
  * Avantages : cela permet de voir d'un coup d'œil toutes les apps qui dépendent de `group` et ainsi d'éviter d'oublier les particularités de chacune lorsqu'on touche directement à l'app abstraite `group` (coucou @charles-zablit 😉)
   * Inconvénient : on perd la structure conventionnelle de django avec toutes les apps dans le même dossier (mais peu de conséquences)
- [ ] Renommer `group` en `asbtract_group` pour bien souligner le fait que cette app est abstraite
   * Avantage : gagner en clarté
   * Inconvénient : opération assez lourde et théoriquement impossible en django puisqu'il faut modifier la bdd. Néanmoins, l'app étant abstraite, aucune donné n'est sauvegardée dans les tables de cette app donc on peut la supprimer puis en recréer une autre facilement, sans migrations de données à faire
- [ ] Ajouter une app `asbtract_page` qui réunira les méthodes communes aux groupes, évènements, posts et étudiants (par exemple : page de détails, réseaux sociaux, slugs...)
   * Avantages : moins de code copié-collé et des fonctionnalités aujourd'hui réservées aux clubs portables plus facilement aux autres pages (réseaux sociaux, slugs et vidéos par exemple)
   * Inconvénient : un niveau d'abstraction supplémentaire pour les groupes
- [ ] Uniformiser les noms des classes pour les apps héritant d'une app abstraite (par exemple, toutes les tables héritant de NamedMembership s'appelleront aussi Namedmembership et non NamedMembership[nom_de_lappli])
   * Avantage : plus besoin de faire des if / else pour les méthodes communes dans les app abstraites (comme les formulaires pour les groupes par exemple) + ne pose pas de problème pour django puisque dans des apps différentes
   * Inconvénient : Pas mal de migrations à faire (mais sans trop de risque, c'est juste du renommage de tables), et pas de soucis pour les autres classes
- [ ] Uniformiser les noms des propriétés des modèles (par exemple, la bannière d'une page s'appelle `banniere` pour un groupe mais `image` pour un event alors qu'il s'agit de la même chose)
   * Avantages : idem qu'au-dessus, plus lgoique et simple à utiliser ensuite, possibilité de faire des templates communs derrière
   * Inconvénient : idem qu'au-dessus, quelques migrations mais juste du renommage donc pas trop risqué

**Comment by hydrielax** [comment]
@charles-zablit @unitrium N'hésitez pas à me dire ce que vous en pensez ;)

**Comment by gheritarish** [comment]
Tu peux détailler ça un peu plus stp ? Je comprends pas ce que tu veux dire… surtout pour les if/else => si ta méthode est définie dans l'app abstraite, logiquement tu peux l'utiliser dans celle qui en hérite, non ?
```
Uniformiser les noms des classes pour les apps héritant d'une app abstraite (par exemple, toutes les tables héritant de NamedMembership s'appelleront aussi Namedmembership et non NamedMembership[nom_de_lappli])
* Avantage : plus besoin de faire des if / else pour les méthodes communes dans les app abstraites (comme les formulaires pour les groupes par exemple) + ne pose pas de problème pour django puisque dans des apps différentes
```

**Comment by hydrielax** [comment]
En fait actuellement le problème est plus pour les formulaires où le code fonctionne de la manière suivante : je vais prendre l'exemple de la page de modification des infos d'un club pour l'exemple :
1. Je fais une requête pour éditer la page d'un club
2. La requête arrive dans `club > urls.py` et va chercher la vue `UpdateGroupView` générique, située dans `group > views.py`, qui est la même pour tous les groupes
3. Dans la classe `UpdateGroupView` on va appeler la fonction `UpdateGroupForm(group)` (dans `group > forms.py` qui va renvoyer la classe formulaire correspondant au groupe passé en argument
4. Dans notre cas, la fonction va tester si le group est d'abord une instance de BDX, puis de Club, puis de Liste, etc.... Comme c'est un club ici (dans l'exemple), elle renvoie la classe `UpdateClubForm` située dans `club > forms.py`.

Pourquoi c'est codé comme ça ? Parce que pour chaque type de groupe on a des champs différents, donc les formulaires doivent être réécrits à chaque fois.

Qu'est-ce que je veux modifier du coup ? En renommant `UpdateClubForm` (et les autres) en `UpdateGroupForm` dans chaque app, je pourrais appeler dans la fonction `UpdateGroupForm(group)` de `group` directement `app(group).forms.UpdateGroupForm` (en pseudo-code) plutôt que de tester chaque instance de groupe et d'écrire en dur le bon nom du formulaire correspondant

**Comment by hydrielax** [comment]
En fait dans le cas de `group` on devrait plus parler d'une app "mère" qu'une app abstraite, puisque les méthodes et classes définies dans `group` ne sont pas définies comme abstraites mais sont directement utilisées dans les apps "enfantes"

**Comment by gheritarish** [comment]
Ouais, donc si je comprends bien, le problème actuel est qu'on n'a pas de redéfinition de méthode pour les "apps enfantes" (bref, les classes qui hérite), mais la création d'une méthode différente.
Du coup, ouais, ce serait cool si on pouvait changer ça :)

**Comment by hydrielax** [comment]
@unitrium @charles-zablit Du coup je vais bientôt m'y atteler, donc si vous avez des remarques je suis preneur

**Comment by charles-zablit** [comment]
> Grouper toutes les apps de type "group" dans un même dossier apps > groups

C'est clairement mieux, malgré la perte de la structure conventionnelle 👍 

> Renommer group en asbtract_group pour bien souligner le fait que cette app est abstraite

Je suis d'accord aussi, ça fait bizarre à voir mais ça me va 👍 

> Ajouter une app asbtract_page qui réunira les méthodes communes aux groupes, évènements, posts et étudiants (par exemple : page de détails, réseaux sociaux, slugs...)

Ca me va aussi, c'est embêtant de devoir se souvenir de toutes les pages à changer 👍

> Uniformiser les noms des classes pour les apps héritant d'une app abstraite (par exemple, toutes les tables héritant de NamedMembership s'appelleront aussi Namedmembership et non NamedMembership[nom_de_lappli])

Euh on va pas avoir des collisions d'imports si jamais on doit utiliser les deux en même temps ? On peut `import as` mais ça enlève un peu de l'intérêt.

> Uniformiser les noms des propriétés des modèles (par exemple, la bannière d'une page s'appelle banniere pour un groupe mais image pour un event alors qu'il s'agit de la même chose)

J'approuve à 200%. Faire attention à ne pas casser nos composants React par contre!

**Comment by unitrium** [comment]
Sur le principe je suis assez d'accord sur la plupart des points.
La convention Python est d'éviter les underscore dans les noms ils me semble donc plutôt renommer en AbstractGroup.

Sinon sur les pages j'avais commencé un truc en septembre mais que j'ai dû interrompre par manque de temps :
C'est implémenter le fait que certaines pages sont pour des objets possédés par quelque chose : un club dans la plupart des cas. J'avais commencé à faire ça pour les évents, les réservations.

Pour les images je ferais bien un truc plus général, une appli image avec un modèle image qui lie le fichier à qui le possède et le contexte d'utilisation (bannière, logo, etc).

**Comment by hydrielax** [comment]
@charles-zablit Pour gérer les conflits d'importations je pensais plutôt à importer le module (du style `from apps.group import model` et ensuite tu utilises `model.NamedMembership` par exemple)

@unitrium Perso la possession d'objets je la voyais pas dans Pages, pour moi la page devait être vraiment hyper généraliste (en englobant les clubs, posts, events et student notamment) et plus unifier la mise en page du site que sa structure. L'idée était plus de mettre là tout le concept du slug aussi

**Comment by hydrielax** [comment]
Et sinon plutôt que abstract_group et abstract_page j'avais pensé à super_group et super_page suite à la remarque @gheritarish

**Comment by unitrium** [comment]
Pour la possession d'objets c'est assez généraliste justement c'est juste une classe dont tu ferais hériter ta vue qui te dit si la personne a le droit d'y accéder pour modifications ou pas.
Donc typiquement on prendrait le slug de l'objet, on trouve le parent et qui est admin de ce parent.

**Comment by hydrielax** [comment]
Oui mais en fait la fonction `is_admin()` (puisqu'au fond c'est ce que tu veux généraliser j'ai l'impression) fonctionne différemment pour les les objets possédés, les groupes et les étudiants. En fait si tu veux vraiment généralisé la possession d'objet il faudrait que ce soir une autre app abstrait au même niveau de groupe qui hériterait de page aussi je pense

**Comment by hydrielax** [comment]
Petit update du coup suite à la décision de passer à un vrai frontend complet : vu qu'une fois le frontend terminé on n'aura plus de templates dans les apps, je pense pour les groupes qu'on pourra passer à une mono-app afin de faciliter la gestion des groupes depuis le front. On pourrait faire une unique table "group", avec une seconde table "groupType" qui contiendrait des champs pour attribuer des paramètres à chaque type (du genre "hasAdress" pour les colocs, etc...)
Pour les champs propres à un type de groupe, on pourrait ajouter ces champs à tous les groupes en facultatif.

**Comment by hydrielax** [comment]
Finalement tous les types de groupes ont été mergés dans une seule app "group", avec une table "groupType" permettant de choisir des paramètres précis pour chaque type de groupe
