### ISSUE TITLE
Create a theme for the React frontend

### ISSUE THREAD

**Issue by hydrielax** [3cn-ecn/nantralPlatform#776]
We need to create a MUI theme for the React frontend of Nantral Platform (for the v2 which will be developped).

## Steps
- [x] 1. Create the light theme
- [x] 2. Create the dark theme
- [x] 3. Add a theme swicth in the user menu, with 3 options: `Auto` (follows system theme), `Dark` and `Light`. `Auto` is default

## Infos
* Generator of the theme: https://bareynol.github.io/mui-theme-creator/
* The color of the graphism chart:
   ![Icones Nantral Platform-24](https://user-images.githubusercontent.com/70099779/190432936-3e7282e8-7a91-434b-bc20-9b13b5baf84f.svg)
   * `#b6b7b7`
   * `#e0e0df`
   * Gradient from `#b6b7b7` to `#e0e0df`
   * `#dc3545`
   * `#ffc107`
   * `#0d6efd`
* Exemples of icons using this colors:
   - repo directory: https://github.com/nantral-platform/nantralPlatform/tree/master/backend/static/img/icons/scalable
   - facebook picture: https://www.facebook.com/photo/?fbid=190244660042979
* How to implements a theme: https://mui.com/material-ui/customization/theming/

**Comment by rravelli** [comment]
Fix dark theme for join button.
Font turn black when selected.
![image](https://user-images.githubusercontent.com/112650656/218433603-4c1ae674-aba7-4c13-9b01-da90e1b6b29e.png)
![image](https://user-images.githubusercontent.com/112650656/218433547-c1a95835-56bb-4e79-952f-e306e86c44fa.png)

**Comment by ManonC12** [comment]
Fix the difference of color between accordions and buttons in the dark theme.
![image](https://user-images.githubusercontent.com/112811926/218436896-a99ed8a4-bc29-42d2-9bb9-752d104d6ca4.png)
